--- Cyberpunk highlight group definitions.
local M = {}

--- Apply all highlight groups.
---@param palette CyberpunkPalette
---@param opts table
function M.apply(palette, opts)
  local hl = vim.api.nvim_set_hl

  -- Core syntax
  hl(0, "Normal", { fg = palette.green, bg = opts.transparent and palette.none or palette.black })
  hl(0, "Comment", { fg = palette.cyan, italic = opts.italic_comments })
  hl(0, "Constant", { fg = palette.blue })
  hl(0, "String", { link = "Constant" })
  hl(0, "Character", { link = "Constant" })
  hl(0, "Number", { link = "Constant" })
  hl(0, "Boolean", { link = "Constant" })
  hl(0, "Float", { link = "Number" })
  hl(0, "Special", { fg = palette.special })
  hl(0, "Tag", { link = "Special" })
  hl(0, "SpecialChar", { link = "Special" })
  hl(0, "Delimiter", { link = "Special" })
  hl(0, "SpecialComment", { link = "Special" })
  hl(0, "Debug", { link = "Special" })
  hl(0, "Identifier", { fg = palette.blue, bold = true })
  hl(0, "Statement", { fg = palette.yellow, bold = true })
  hl(0, "Label", { link = "Statement" })
  hl(0, "Keyword", { fg = palette.yellow, bold = opts.bold_keywords, italic = opts.italic_keywords })
  hl(0, "Exception", { link = "Statement" })
  hl(0, "PreProc", { fg = palette.cyan })
  hl(0, "Include", { link = "PreProc" })
  hl(0, "Define", { link = "PreProc" })
  hl(0, "Macro", { link = "PreProc" })
  hl(0, "PreCondit", { link = "PreProc" })
  hl(0, "Type", { fg = palette.yellow, bold = true })
  hl(0, "StorageClass", { link = "Type" })
  hl(0, "Structure", { link = "Type" })
  hl(0, "Typedef", { link = "Type" })
  hl(0, "Function", { fg = palette.green, bold = opts.bold_functions })
  hl(0, "Repeat", { fg = palette.yellow })
  hl(0, "Conditional", { link = "Repeat" })
  hl(0, "Operator", { fg = palette.red })
  hl(0, "Ignore", { fg = palette.black })
  hl(0, "Error", { fg = palette.red, bg = palette.dark_purple })
  hl(0, "Todo", { fg = palette.blue, bg = palette.yellow })

  -- Popup menu
  hl(0, "Pmenu", { fg = palette.black, bg = palette.green })
  hl(0, "PmenuSel", { fg = palette.blue, bg = palette.yellow })
  hl(0, "PmenuKind", { fg = palette.blue, bg = palette.green })
  hl(0, "PmenuKindSel", { fg = palette.black, bg = palette.yellow })
  hl(0, "PmenuExtra", { fg = palette.dark_fg, bg = palette.green })
  hl(0, "PmenuExtraSel", { fg = palette.black, bg = palette.yellow })
  hl(0, "PmenuSbar", { bg = palette.dark_bg })
  hl(0, "PmenuThumb", { bg = palette.dark_fg })

  -- UI elements
  hl(0, "LineNr", { fg = palette.dark_fg })
  hl(0, "CursorLineNr", { fg = palette.yellow, bold = true })
  hl(0, "CursorLine", { bg = palette.dark_bg })
  hl(0, "CursorColumn", { bg = palette.dark_bg })
  hl(0, "ColorColumn", { bg = palette.dark_bg })
  hl(0, "Visual", { bg = palette.visual })
  hl(0, "VisualNOS", { bg = palette.visual })
  hl(0, "Search", { fg = palette.black, bg = palette.yellow })
  hl(0, "IncSearch", { fg = palette.black, bg = palette.cyan })
  hl(0, "MatchParen", { fg = palette.yellow, bg = palette.visual })
  hl(0, "StatusLine", { fg = palette.green, bg = palette.dark_bg })
  hl(0, "StatusLineNC", { fg = palette.dark_fg, bg = palette.dark_bg })
  hl(0, "VertSplit", { fg = palette.dark_fg })
  hl(0, "WinSeparator", { fg = palette.dark_fg })
  hl(0, "Folded", { fg = palette.cyan, bg = palette.dark_bg })
  hl(0, "FoldColumn", { fg = palette.cyan, bg = palette.dark_bg })
  hl(0, "SignColumn", { bg = palette.none })
  hl(0, "NonText", { fg = palette.dark_fg })
  hl(0, "SpecialKey", { fg = palette.dark_fg })
  hl(0, "Title", { fg = palette.yellow, bold = true })
  hl(0, "Directory", { fg = palette.cyan })
  hl(0, "WildMenu", { fg = palette.black, bg = palette.yellow })
  hl(0, "TabLine", { fg = palette.dark_fg, bg = palette.dark_bg })
  hl(0, "TabLineSel", { fg = palette.green, bg = palette.black })
  hl(0, "TabLineFill", { bg = palette.dark_bg })
  hl(0, "EndOfBuffer", { fg = palette.black })
  hl(0, "Substitute", { fg = palette.black, bg = palette.red })
  hl(0, "QuickFixLine", { fg = palette.black, bg = palette.yellow })
  hl(0, "Conceal", { fg = palette.cyan })
  hl(0, "Whitespace", { fg = palette.dark_fg })
  hl(0, "NormalNC", { fg = palette.green, bg = opts.transparent and palette.none or palette.black })

  -- Diff
  hl(0, "DiffAdd", { bg = palette.diff_green })
  hl(0, "DiffChange", { bg = palette.diff_blue })
  hl(0, "DiffDelete", { fg = palette.red, bg = palette.diff_red })
  hl(0, "DiffText", { bg = palette.dark_purple, bold = true })

  -- Diagnostics (Neovim LSP)
  hl(0, "DiagnosticError", { fg = palette.red })
  hl(0, "DiagnosticWarn", { fg = palette.yellow })
  hl(0, "DiagnosticInfo", { fg = palette.blue })
  hl(0, "DiagnosticHint", { fg = palette.cyan })
  hl(0, "DiagnosticOk", { fg = palette.green })
  hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = palette.red })
  hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = palette.yellow })
  hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = palette.blue })
  hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = palette.cyan })
  hl(0, "DiagnosticUnderlineOk", { undercurl = true, sp = palette.green })
  hl(0, "DiagnosticSignError", { fg = palette.red })
  hl(0, "DiagnosticSignWarn", { fg = palette.yellow })
  hl(0, "DiagnosticSignInfo", { fg = palette.blue })
  hl(0, "DiagnosticSignHint", { fg = palette.cyan })
  hl(0, "DiagnosticSignOk", { fg = palette.green })
  hl(0, "DiagnosticVirtualTextError", { fg = palette.red, bg = palette.diff_red })
  hl(0, "DiagnosticVirtualTextWarn", { fg = palette.yellow, bg = palette.dark_bg })
  hl(0, "DiagnosticVirtualTextInfo", { fg = palette.blue, bg = palette.diff_blue })
  hl(0, "DiagnosticVirtualTextHint", { fg = palette.cyan, bg = palette.dark_bg })
  hl(0, "DiagnosticVirtualTextOk", { fg = palette.green, bg = palette.diff_green })
  hl(0, "DiagnosticFloatingError", { fg = palette.red })
  hl(0, "DiagnosticFloatingWarn", { fg = palette.yellow })
  hl(0, "DiagnosticFloatingInfo", { fg = palette.blue })
  hl(0, "DiagnosticFloatingHint", { fg = palette.cyan })
  hl(0, "DiagnosticFloatingOk", { fg = palette.green })

  -- Spell
  hl(0, "SpellBad", { undercurl = true, sp = palette.red })
  hl(0, "SpellCap", { undercurl = true, sp = palette.blue })
  hl(0, "SpellRare", { undercurl = true, sp = palette.special })
  hl(0, "SpellLocal", { undercurl = true, sp = palette.cyan })

  -- Treesitter
  hl(0, "@comment", { link = "Comment" })
  hl(0, "@constant", { link = "Constant" })
  hl(0, "@constant.builtin", { fg = palette.blue, bold = true })
  hl(0, "@constant.macro", { link = "Macro" })
  hl(0, "@string", { link = "String" })
  hl(0, "@string.escape", { fg = palette.special })
  hl(0, "@string.regex", { fg = palette.cyan })
  hl(0, "@string.special", { fg = palette.special })
  hl(0, "@character", { link = "Character" })
  hl(0, "@number", { link = "Number" })
  hl(0, "@boolean", { link = "Boolean" })
  hl(0, "@float", { link = "Float" })
  hl(0, "@function", { fg = palette.green, bold = opts.bold_functions })
  hl(0, "@function.builtin", { fg = palette.green, bold = true })
  hl(0, "@function.call", { fg = palette.green })
  hl(0, "@function.macro", { fg = palette.cyan })
  hl(0, "@method", { fg = palette.green })
  hl(0, "@method.call", { fg = palette.green })
  hl(0, "@constructor", { fg = palette.yellow })
  hl(0, "@parameter", { fg = palette.blue, italic = true })
  hl(0, "@keyword", { fg = palette.yellow, bold = opts.bold_keywords, italic = opts.italic_keywords })
  hl(0, "@keyword.function", { fg = palette.yellow, italic = opts.italic_keywords })
  hl(0, "@keyword.operator", { fg = palette.red })
  hl(0, "@keyword.return", { fg = palette.yellow, bold = true })
  hl(0, "@conditional", { link = "Conditional" })
  hl(0, "@repeat", { link = "Repeat" })
  hl(0, "@label", { link = "Label" })
  hl(0, "@operator", { link = "Operator" })
  hl(0, "@exception", { link = "Exception" })
  hl(0, "@variable", { fg = palette.green })
  hl(0, "@variable.builtin", { fg = palette.blue, italic = true })
  hl(0, "@type", { link = "Type" })
  hl(0, "@type.builtin", { fg = palette.yellow })
  hl(0, "@type.definition", { link = "Typedef" })
  hl(0, "@type.qualifier", { fg = palette.yellow, italic = true })
  hl(0, "@namespace", { fg = palette.cyan })
  hl(0, "@include", { link = "Include" })
  hl(0, "@preproc", { link = "PreProc" })
  hl(0, "@define", { link = "Define" })
  hl(0, "@field", { fg = palette.blue })
  hl(0, "@property", { fg = palette.blue })
  hl(0, "@punctuation.bracket", { fg = palette.special })
  hl(0, "@punctuation.delimiter", { fg = palette.special })
  hl(0, "@punctuation.special", { fg = palette.cyan })
  hl(0, "@tag", { fg = palette.yellow })
  hl(0, "@tag.attribute", { fg = palette.green, italic = true })
  hl(0, "@tag.delimiter", { fg = palette.special })
  hl(0, "@text", { fg = palette.green })
  hl(0, "@text.strong", { bold = true })
  hl(0, "@text.emphasis", { italic = true })
  hl(0, "@text.underline", { underline = true })
  hl(0, "@text.strike", { strikethrough = true })
  hl(0, "@text.title", { fg = palette.yellow, bold = true })
  hl(0, "@text.literal", { fg = palette.cyan })
  hl(0, "@text.uri", { fg = palette.blue, underline = true })
  hl(0, "@text.reference", { fg = palette.blue })

  -- LSP semantic tokens
  hl(0, "@lsp.type.class", { link = "Type" })
  hl(0, "@lsp.type.decorator", { fg = palette.cyan })
  hl(0, "@lsp.type.enum", { link = "Type" })
  hl(0, "@lsp.type.enumMember", { link = "Constant" })
  hl(0, "@lsp.type.function", { link = "@function" })
  hl(0, "@lsp.type.interface", { fg = palette.cyan, bold = true })
  hl(0, "@lsp.type.keyword", { link = "@keyword" })
  hl(0, "@lsp.type.macro", { link = "Macro" })
  hl(0, "@lsp.type.method", { link = "@method" })
  hl(0, "@lsp.type.namespace", { link = "@namespace" })
  hl(0, "@lsp.type.parameter", { link = "@parameter" })
  hl(0, "@lsp.type.property", { link = "@property" })
  hl(0, "@lsp.type.struct", { link = "Structure" })
  hl(0, "@lsp.type.type", { link = "Type" })
  hl(0, "@lsp.type.typeParameter", { fg = palette.yellow, italic = true })
  hl(0, "@lsp.type.variable", { link = "@variable" })
  hl(0, "@lsp.mod.deprecated", { strikethrough = true })

  -- Floating windows
  hl(0, "NormalFloat", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "FloatBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "FloatTitle", { fg = palette.yellow, bold = true })
  hl(0, "FloatFooter", { fg = palette.dark_fg })

  -- Messages
  hl(0, "ErrorMsg", { fg = palette.red, bold = true })
  hl(0, "WarningMsg", { fg = palette.yellow, bold = true })
  hl(0, "ModeMsg", { fg = palette.green, bold = true })
  hl(0, "MoreMsg", { fg = palette.cyan })
  hl(0, "MsgArea", { fg = palette.green })
  hl(0, "Question", { fg = palette.cyan })

  -- Cursor
  hl(0, "Cursor", { fg = palette.black, bg = palette.green })
  hl(0, "lCursor", { fg = palette.black, bg = palette.green })
  hl(0, "CursorIM", { fg = palette.black, bg = palette.green })
  hl(0, "TermCursor", { fg = palette.black, bg = palette.green })
  hl(0, "TermCursorNC", { fg = palette.black, bg = palette.dark_fg })

  -- WinBar (Neovim 0.8+)
  hl(0, "WinBar", { fg = palette.green, bold = true })
  hl(0, "WinBarNC", { fg = palette.dark_fg })

  -- Neovim 0.10+ Treesitter capture renames
  hl(0, "@variable.member", { fg = palette.blue })
  hl(0, "@variable.parameter", { fg = palette.blue, italic = true })
  hl(0, "@function.method", { fg = palette.green })
  hl(0, "@function.method.call", { fg = palette.green })
  hl(0, "@module", { fg = palette.cyan })
  hl(0, "@string.regexp", { fg = palette.cyan })
  hl(0, "@markup.heading", { fg = palette.yellow, bold = true })
  hl(0, "@markup.strong", { bold = true })
  hl(0, "@markup.italic", { italic = true })
  hl(0, "@markup.strikethrough", { strikethrough = true })
  hl(0, "@markup.underline", { underline = true })
  hl(0, "@markup.link", { fg = palette.blue, underline = true })
  hl(0, "@markup.link.label", { fg = palette.blue })
  hl(0, "@markup.link.url", { fg = palette.blue, underline = true })
  hl(0, "@markup.raw", { fg = palette.cyan })
  hl(0, "@markup.list", { fg = palette.special })

  -- Git signs (gitsigns.nvim)
  hl(0, "GitSignsAdd", { fg = palette.green })
  hl(0, "GitSignsChange", { fg = palette.blue })
  hl(0, "GitSignsDelete", { fg = palette.red })

  -- Telescope
  hl(0, "TelescopeNormal", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "TelescopeBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "TelescopeTitle", { fg = palette.yellow, bold = true })
  hl(0, "TelescopePromptNormal", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "TelescopePromptBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "TelescopePromptTitle", { fg = palette.yellow, bold = true })
  hl(0, "TelescopePromptPrefix", { fg = palette.red })
  hl(0, "TelescopePreviewTitle", { fg = palette.yellow, bold = true })
  hl(0, "TelescopeResultsTitle", { fg = palette.yellow, bold = true })
  hl(0, "TelescopeSelection", { fg = palette.cyan, bg = palette.visual })
  hl(0, "TelescopeSelectionCaret", { fg = palette.red })
  hl(0, "TelescopeMatching", { fg = palette.yellow, bold = true })

  -- nvim-cmp
  hl(0, "CmpItemAbbrMatch", { fg = palette.yellow, bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = palette.yellow })
  hl(0, "CmpItemKindFunction", { fg = palette.green })
  hl(0, "CmpItemKindMethod", { fg = palette.green })
  hl(0, "CmpItemKindVariable", { fg = palette.blue })
  hl(0, "CmpItemKindField", { fg = palette.blue })
  hl(0, "CmpItemKindProperty", { fg = palette.blue })
  hl(0, "CmpItemKindKeyword", { fg = palette.yellow })
  hl(0, "CmpItemKindClass", { fg = palette.yellow })
  hl(0, "CmpItemKindStruct", { fg = palette.yellow })
  hl(0, "CmpItemKindInterface", { fg = palette.cyan })
  hl(0, "CmpItemKindModule", { fg = palette.cyan })
  hl(0, "CmpItemKindConstant", { fg = palette.blue })
  hl(0, "CmpItemKindEnum", { fg = palette.yellow })
  hl(0, "CmpItemKindEnumMember", { fg = palette.blue })
  hl(0, "CmpItemKindSnippet", { fg = palette.special })
  hl(0, "CmpItemKindText", { fg = palette.green })
  hl(0, "CmpItemKindValue", { fg = palette.blue })
  hl(0, "CmpItemMenu", { fg = palette.dark_fg })

  -- nvim-tree
  hl(0, "NvimTreeNormal", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NvimTreeFolderName", { fg = palette.cyan })
  hl(0, "NvimTreeOpenedFolderName", { fg = palette.cyan, bold = true })
  hl(0, "NvimTreeEmptyFolderName", { fg = palette.dark_fg })
  hl(0, "NvimTreeFolderIcon", { fg = palette.cyan })
  hl(0, "NvimTreeRootFolder", { fg = palette.yellow, bold = true })
  hl(0, "NvimTreeGitDirty", { fg = palette.yellow })
  hl(0, "NvimTreeGitNew", { fg = palette.green })
  hl(0, "NvimTreeGitDeleted", { fg = palette.red })
  hl(0, "NvimTreeSpecialFile", { fg = palette.special })
  hl(0, "NvimTreeIndentMarker", { fg = palette.dark_fg })

  -- lazy.nvim
  hl(0, "LazyButton", { fg = palette.green, bg = palette.dark_bg })
  hl(0, "LazyButtonActive", { fg = palette.black, bg = palette.green })
  hl(0, "LazyH1", { fg = palette.black, bg = palette.green, bold = true })
  hl(0, "LazyH2", { fg = palette.yellow, bold = true })
  hl(0, "LazySpecial", { fg = palette.cyan })
  hl(0, "LazyCommit", { fg = palette.dark_fg })
  hl(0, "LazyCommitType", { fg = palette.yellow })

  -- indent-blankline
  hl(0, "IblIndent", { fg = palette.dark_bg })
  hl(0, "IblScope", { fg = palette.dark_fg })

  -- which-key
  hl(0, "WhichKey", { fg = palette.cyan })
  hl(0, "WhichKeyGroup", { fg = palette.yellow })
  hl(0, "WhichKeyDesc", { fg = palette.green })
  hl(0, "WhichKeySeparator", { fg = palette.dark_fg })
  hl(0, "WhichKeyFloat", { bg = palette.dark_bg })

  -- nvim-notify
  hl(0, "NotifyERRORBorder", { fg = palette.red })
  hl(0, "NotifyERRORTitle", { fg = palette.red })
  hl(0, "NotifyERRORIcon", { fg = palette.red })
  hl(0, "NotifyWARNBorder", { fg = palette.yellow })
  hl(0, "NotifyWARNTitle", { fg = palette.yellow })
  hl(0, "NotifyWARNIcon", { fg = palette.yellow })
  hl(0, "NotifyINFOBorder", { fg = palette.blue })
  hl(0, "NotifyINFOTitle", { fg = palette.blue })
  hl(0, "NotifyINFOIcon", { fg = palette.blue })

  -- Noice
  hl(0, "NoiceCmdline", { fg = palette.green, bg = opts.transparent and palette.none or palette.black })
  hl(0, "NoiceCmdlineIcon", { fg = palette.cyan })
  hl(0, "NoiceCmdlineIconSearch", { fg = palette.yellow })
  hl(0, "NoiceCmdlinePrompt", { fg = palette.yellow, bold = true })
  hl(0, "NoiceCmdlinePopup", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceCmdlinePopupBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceCmdlinePopupTitle", { fg = palette.yellow, bold = true })
  hl(0, "NoiceCmdlinePopupBorderSearch", {
    fg = palette.yellow,
    bg = opts.transparent and palette.none or palette.dark_bg,
  })
  hl(0, "NoiceConfirm", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceConfirmBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceCursor", { fg = palette.black, bg = palette.green })
  hl(0, "NoiceMini", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoicePopup", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoicePopupBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoicePopupmenu", { fg = palette.black, bg = palette.green })
  hl(0, "NoicePopupmenuBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoicePopupmenuMatch", { fg = palette.yellow, bold = true })
  hl(0, "NoicePopupmenuSelected", { fg = palette.blue, bg = palette.yellow })
  hl(0, "NoiceScrollbar", { bg = palette.dark_bg })
  hl(0, "NoiceScrollbarThumb", { bg = palette.dark_fg })
  hl(0, "NoiceSplit", { fg = palette.green, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceSplitBorder", { fg = palette.cyan, bg = opts.transparent and palette.none or palette.dark_bg })
  hl(0, "NoiceVirtualText", { fg = palette.blue })
  hl(0, "NoiceFormatProgressDone", { fg = palette.black, bg = palette.green })
  hl(0, "NoiceFormatProgressTodo", { bg = palette.dark_bg })
  hl(0, "NoiceFormatEvent", { fg = palette.dark_fg })
  hl(0, "NoiceFormatKind", { fg = palette.dark_fg })
  hl(0, "NoiceFormatDate", { fg = palette.special })
  hl(0, "NoiceFormatConfirm", { bg = palette.dark_bg })
  hl(0, "NoiceFormatConfirmDefault", { bg = palette.visual })
  hl(0, "NoiceFormatTitle", { fg = palette.yellow, bold = true })
  hl(0, "NoiceFormatLevelDebug", { fg = palette.dark_fg })
  hl(0, "NoiceFormatLevelTrace", { fg = palette.dark_fg })
  hl(0, "NoiceFormatLevelOff", { fg = palette.dark_fg })
  hl(0, "NoiceFormatLevelInfo", { fg = palette.blue })
  hl(0, "NoiceFormatLevelWarn", { fg = palette.yellow })
  hl(0, "NoiceFormatLevelError", { fg = palette.red })
  hl(0, "NoiceLspProgressSpinner", { fg = palette.cyan })
  hl(0, "NoiceLspProgressTitle", { fg = palette.dark_fg })
  hl(0, "NoiceLspProgressClient", { fg = palette.yellow, bold = true })
  hl(0, "NoiceCompletionItemMenu", { fg = palette.dark_fg })
  hl(0, "NoiceCompletionItemWord", { fg = palette.green })
  hl(0, "NoiceCompletionItemKindDefault", { fg = palette.special })
  hl(0, "NoiceCompletionItemKindFunction", { fg = palette.green })
  hl(0, "NoiceCompletionItemKindMethod", { fg = palette.green })
  hl(0, "NoiceCompletionItemKindClass", { fg = palette.yellow })
  hl(0, "NoiceCompletionItemKindInterface", { fg = palette.cyan })
  hl(0, "NoiceCompletionItemKindModule", { fg = palette.cyan })
  hl(0, "NoiceCompletionItemKindStruct", { fg = palette.yellow })
  hl(0, "NoiceCompletionItemKindKeyword", { fg = palette.yellow })
  hl(0, "NoiceCompletionItemKindValue", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindProperty", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindConstant", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindSnippet", { fg = palette.special })
  hl(0, "NoiceCompletionItemKindFolder", { fg = palette.cyan })
  hl(0, "NoiceCompletionItemKindText", { fg = palette.green })
  hl(0, "NoiceCompletionItemKindVariable", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindField", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindEnum", { fg = palette.yellow })
  hl(0, "NoiceCompletionItemKindEnumMember", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindConstructor", { fg = palette.yellow })
  hl(0, "NoiceCompletionItemKindColor", { fg = palette.special })
  hl(0, "NoiceCompletionItemKindUnit", { fg = palette.blue })
  hl(0, "NoiceCompletionItemKindFile", { fg = palette.green })

  -- Apply user overrides
  if opts.overrides then
    for group, settings in pairs(opts.overrides) do
      hl(0, group, settings)
    end
  end
end

return M
